import type { Metadata } from "next";
import { Cardo, Geist, Inter } from "next/font/google";
import "./globals.css";

import Footer from "@/components/common/footer/Footer";
import Navbar from "@/components/common/header/Navbar";
import Main from "@/components/layout/Main";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-inter",
  display: "swap",
});

const cardo = Cardo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cardo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={cn(
        "h-full",
        "antialiased",
        inter.variable,
        cardo.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Navbar />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
